### PR TITLE
Add decidim-cleaner

### PR DESCRIPTION
**Pull request by armandfardeau**
#### :tophat: Description
Add decidim cleaner

### CODE REVIEW

**Review by eliegaboriau — CHANGES_REQUESTED** [review]
I think you should add the sidekiq queues too

**Comment by armandfardeau** [comment]
Please ignore codeclimate error for now

**Review by eliegaboriau — APPROVED** [review]

**Review by paulinebessoles — DISMISSED** [review]

**Review by Quentinchampenois — DISMISSED** [review]

**Comment by Quentinchampenois** [comment]
I just noticed conflicts on PR, can you fix conflicts please ?

**Comment by paulinebessoles** [comment]
I converted this PR to draft because we shouldn't merge it before https://github.com/OpenSourcePolitics/decidim-module-cleaner/pull/9 is backported to the 0.26 branch, as it could cause issues to production data.

**Review by Quentinchampenois — APPROVED** [review]

**Review by paulinebessoles — APPROVED** [review]

**Pull request merged**
