### PR TITLE
Add required gems and bump decidim

### PR DESCRIPTION
**Pull request by armandfardeau**

### CODE REVIEW

**Comment by virgile-dev** [comment]
Hello @armandfardeau  , 
I'll be reviewing this :)
Thanks for adding the captcha module to the gem file and updating to 0.24, Is it configured to point to your API or doesn't it extra configuration ? (I haven't tried to run it locally).

Also I'd like to withdrawing navbar_links from the bundle as decidim-awesome provides a better solution. Do you want to do it in this PR or shoud we make another ?

**Comment by armandfardeau** [comment]
> Hello @armandfardeau ,
> I'll be reviewing this :)
> Thanks for adding the captcha module to the gem file and updating to 0.24, Is it configured to point to your API or doesn't it extra configuration ? (I haven't tried to run it locally).
> 
> Also I'd like to withdrawing navbar_links from the bundle as decidim-awesome provides a better solution. Do you want to do it in this PR or shoud we make another ?

Hi we should do it in another PR

**Comment by armandfardeau** [comment]
branch can be tested here: https://decidim-app-test.opensourcepolitics.net/

**Review by MoretS — APPROVED** [review]
@armandfardeau Thanks!

**Comment by virgile-dev** [comment]
I tested the link provided by @armandfardeau (thanks !)
I left an issue on the question captcha repo : https://github.com/OpenSourcePolitics/decidim-module-question_captcha/issues/8 

I noticed the deployment still included decidim url aliases which doesn't appear to be working
Capture d’écran 2021-07-26 à 17 27 28

Who could open the PR to withdraw navbar module ?

**Comment by armandfardeau** [comment]
> I tested the link provided by @armandfardeau (thanks !)
> I left an issue on the question captcha repo : [OpenSourcePolitics/decidim-module-question_captcha#8](https://github.com/OpenSourcePolitics/decidim-module-question_captcha/issues/8)
> 
> I noticed the deployment still included decidim url aliases which doesn't appear to be working
> Capture d’écran 2021-07-26 à 17 27 28
> 
> Who could open the PR to withdraw navbar module ?

Regarding url-aliases, I think you're using it wrong, have you tried to switch source and destination?

I'm opening the P.R.

**Comment by virgile-dev** [comment]
Yeah, decidim url aliases works well. sorry false alert

**Pull request merged**
