### PR TITLE
add cofe locales

### PR DESCRIPTION
**Pull request by luciegrau**
#### :tophat: Description
*Please describe your pull request.*
This PR adds new locales from the COFE translations that are not translated in Crowdin in `config/locales`

#### :pushpin: Related Issues
*Link your PR to an issue*
Related to https://www.notion.so/opensourcepolitics/Real-Deal-Ajout-trads-COFE-4a4575ad4ef641e18535f6cefaae525d 

#### Testing
*Describe the best way to test or validate your PR.*
* Add the new available locales in your `.env` file 
* Log in as a user 
* Compare the translations in different languages with the available translations in the .yml files. 

#### Tasks
- [X] Add translations .yml files in `config/locales`

### CODE REVIEW

**Review by eliegaboriau — APPROVED** [review]
Congratulations @luciegrau on your first pr, i hope it's the first to many more ! 👏 👏 🥳 🥳

**Review by paulinebessoles — CHANGES_REQUESTED** [review]
Thank you and congrats for your first pull request @luciegrau !

Locales are working great in local, but I encounter an issue on the search that seems to be related to this PR, as you can see in the screenshot below. 

Capture d’écran 2023-05-10 à 11 01 44

Stacktrace: 
```
ActionView::Template::Error (no implicit conversion of nil into String):
     9:       <%= render partial: "filters" %>
    10:     </div>
    11:     <div id="results" class="columns mediumlarge-8 large-9">
    12:       <%= cell "decidim/search_results", @sections, params: params %>
    13:     </div>
    14:   </div>
    15: </div>
  
activesupport (6.0.6.1) lib/active_support/number_helper/number_to_currency_converter.rb:20:in `gsub'
activesupport (6.0.6.1) lib/active_support/number_helper/number_to_currency_converter.rb:20:in `convert'
activesupport (6.0.6.1) lib/active_support/number_helper/number_converter.rb:134:in `execute'
activesupport (6.0.6.1) lib/active_support/number_helper/number_converter.rb:120:in `convert'
activesupport (6.0.6.1) lib/active_support/number_helper.rb:115:in `number_to_currency'
decidim-budgets (0.26.5) app/helpers/decidim/budgets/projects_helper.rb:11:in `budget_to_currency'
decidim-budgets (0.26.5) app/cells/decidim/budgets/budget_m/data.erb:8:in `__tilt_159960'
tilt (2.1.0) lib/tilt/template.rb:191:in `bind_call'
tilt (2.1.0) lib/tilt/template.rb:191:in `evaluate'
tilt (2.1.0) lib/tilt/template.rb:109:in `render'
cells (4.1.7) lib/cell/view_model.rb:118:in `render_template'
decidim-core (0.26.5) lib/decidim/view_model.rb:45:in `block in render_template'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:40:in `render_template'
cells (4.1.7) lib/cell/view_model.rb:110:in `render_to_string'
cells (4.1.7) lib/cell/layout.rb:23:in `render_to_string'
cells (4.1.7) lib/cell/view_model.rb:104:in `render'
decidim-core (0.26.5) app/cells/decidim/card_m/show.erb:19:in `__tilt_159960'
tilt (2.1.0) lib/tilt/template.rb:191:in `bind_call'
tilt (2.1.0) lib/tilt/template.rb:191:in `evaluate'
tilt (2.1.0) lib/tilt/template.rb:109:in `render'
cells (4.1.7) lib/cell/view_model.rb:118:in `render_template'
decidim-core (0.26.5) lib/decidim/view_model.rb:45:in `block in render_template'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:40:in `render_template'
cells (4.1.7) lib/cell/view_model.rb:110:in `render_to_string'
cells (4.1.7) lib/cell/layout.rb:23:in `render_to_string'
cells (4.1.7) lib/cell/view_model.rb:104:in `render'
decidim-core (0.26.5) app/cells/decidim/card_m_cell.rb:16:in `show'
cells (4.1.7) lib/cell/view_model.rb:114:in `render_state'
cells (4.1.7) lib/cell/caching.rb:46:in `render_state'
cells (4.1.7) lib/cell/view_model.rb:92:in `call'
cells-rails (0.1.5) lib/cell/rails.rb:56:in `call'
decidim-core (0.26.5) lib/decidim/view_model.rb:33:in `block in call'
decidim-core (0.26.5) lib/decidim/view_model.rb:51:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:50:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:32:in `call'
cells (4.1.7) lib/cell/view_model.rb:125:in `to_s'
cells (4.1.7) lib/cell/view_model.rb:93:in `call'
cells-rails (0.1.5) lib/cell/rails.rb:56:in `call'
decidim-core (0.26.5) lib/decidim/view_model.rb:33:in `block in call'
decidim-core (0.26.5) lib/decidim/view_model.rb:51:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:50:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:32:in `call'
cells (4.1.7) lib/cell/view_model.rb:125:in `to_s'
cells (4.1.7) lib/cell/view_model.rb:93:in `call'
cells-rails (0.1.5) lib/cell/rails.rb:56:in `call'
decidim-core (0.26.5) lib/decidim/view_model.rb:33:in `block in call'
decidim-core (0.26.5) lib/decidim/view_model.rb:51:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:50:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:32:in `call'
cells (4.1.7) lib/cell/view_model.rb:125:in `to_s'
decidim-core (0.26.5) app/cells/decidim/search_results_section/show.erb:25:in `join'
decidim-core (0.26.5) app/cells/decidim/search_results_section/show.erb:25:in `__tilt_159960'
tilt (2.1.0) lib/tilt/template.rb:191:in `bind_call'
tilt (2.1.0) lib/tilt/template.rb:191:in `evaluate'
tilt (2.1.0) lib/tilt/template.rb:109:in `render'
cells (4.1.7) lib/cell/view_model.rb:118:in `render_template'
decidim-core (0.26.5) lib/decidim/view_model.rb:45:in `block in render_template'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:40:in `render_template'
cells (4.1.7) lib/cell/view_model.rb:110:in `render_to_string'
cells (4.1.7) lib/cell/layout.rb:23:in `render_to_string'
cells (4.1.7) lib/cell/view_model.rb:104:in `render'
decidim-core (0.26.5) app/cells/decidim/search_results_section_cell.rb:12:in `show'
cells (4.1.7) lib/cell/view_model.rb:114:in `render_state'
cells (4.1.7) lib/cell/caching.rb:46:in `render_state'
cells (4.1.7) lib/cell/view_model.rb:92:in `call'
cells-rails (0.1.5) lib/cell/rails.rb:56:in `call'
decidim-core (0.26.5) lib/decidim/view_model.rb:33:in `block in call'
decidim-core (0.26.5) lib/decidim/view_model.rb:51:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:50:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:32:in `call'
cells (4.1.7) lib/cell/view_model.rb:125:in `to_s'
decidim-core (0.26.5) app/cells/decidim/search_results/show.erb:9:in `join'
decidim-core (0.26.5) app/cells/decidim/search_results/show.erb:9:in `__tilt_159960'
tilt (2.1.0) lib/tilt/template.rb:191:in `bind_call'
tilt (2.1.0) lib/tilt/template.rb:191:in `evaluate'
tilt (2.1.0) lib/tilt/template.rb:109:in `render'
cells (4.1.7) lib/cell/view_model.rb:118:in `render_template'
decidim-core (0.26.5) lib/decidim/view_model.rb:45:in `block in render_template'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:40:in `render_template'
cells (4.1.7) lib/cell/view_model.rb:110:in `render_to_string'
cells (4.1.7) lib/cell/layout.rb:23:in `render_to_string'
cells (4.1.7) lib/cell/view_model.rb:104:in `render'
decidim-core (0.26.5) app/cells/decidim/search_results_cell.rb:10:in `show'
cells (4.1.7) lib/cell/view_model.rb:114:in `render_state'
cells (4.1.7) lib/cell/caching.rb:46:in `render_state'
cells (4.1.7) lib/cell/view_model.rb:92:in `call'
cells-rails (0.1.5) lib/cell/rails.rb:56:in `call'
decidim-core (0.26.5) lib/decidim/view_model.rb:33:in `block in call'
decidim-core (0.26.5) lib/decidim/view_model.rb:51:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:50:in `instrument'
decidim-core (0.26.5) lib/decidim/view_model.rb:32:in `call'
cells (4.1.7) lib/cell/view_model.rb:125:in `to_s'
actionview (6.0.6.1) lib/action_view/buffers.rb:29:in `<<'
decidim-core (0.26.5) app/views/decidim/searches/index.html.erb:12
actionview (6.0.6.1) lib/action_view/base.rb:274:in `_run'
actionview (6.0.6.1) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.6.1) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.6.1) lib/action_view/template.rb:385:in `instrument_render_template'
actionview (6.0.6.1) lib/action_view/template.rb:183:in `render'
actionview (6.0.6.1) lib/action_view/renderer/template_renderer.rb:58:in `block (2 levels) in render_template'
actionview (6.0.6.1) lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.6.1) lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
actionview (6.0.6.1) lib/action_view/renderer/template_renderer.rb:57:in `block in render_template'
actionview (6.0.6.1) lib/action_view/renderer/template_renderer.rb:65:in `render_with_layout'
actionview (6.0.6.1) lib/action_view/renderer/template_renderer.rb:56:in `render_template'
actionview (6.0.6.1) lib/action_view/renderer/template_renderer.rb:13:in `render'
actionview (6.0.6.1) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.0.6.1) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.0.6.1) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (6.0.6.1) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.6.1) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (6.0.6.1) lib/action_controller/metal/streaming.rb:218:in `_render_template'
actionview (6.0.6.1) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.0.6.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.0.6.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.0.6.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.0.6.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.0.6.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (6.0.6.1) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/Users/pops/.rbenv/versions/2.7.5/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
activesupport (6.0.6.1) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.0.6.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (6.0.6.1) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (6.0.6.1) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.0.6.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
wicked_pdf (2.6.3) lib/wicked_pdf/pdf_helper.rb:18:in `render'
actionpack (6.0.6.1) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (6.0.6.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
actionpack (6.0.6.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
actionpack (6.0.6.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.6.1) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.6.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.6.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.6.1) lib/active_support/callbacks.rb:112:in `block in run_callbacks'
activesupport (6.0.6.1) lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
decidim-core (0.26.5) app/controllers/concerns/decidim/use_organization_time_zone.rb:21:in `use_organization_time_zone'
activesupport (6.0.6.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
i18n (1.13.0) lib/i18n.rb:322:in `with_locale'
decidim-core (0.26.5) app/controllers/concerns/decidim/locale_switcher.rb:24:in `switch_locale'
activesupport (6.0.6.1) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
activesupport (6.0.6.1) lib/active_support/callbacks.rb:139:in `run_callbacks'
actionpack (6.0.6.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.6.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.6.1) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.6.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.6.1) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.6.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.6.1) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.6.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.6.1) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.6.1) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.6.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.6.1) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.6.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.6.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
railties (6.0.6.1) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.6.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.6.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.6.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.6.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.6.1) lib/action_dispatch/routing/route_set.rb:834:in `call'
batch-loader (1.5.0) lib/batch_loader/middleware.rb:11:in `call'
omniauth (2.1.1) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.1) lib/omniauth/builder.rb:44:in `call'
omniauth (2.1.1) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.1) lib/omniauth/builder.rb:44:in `call'
omniauth (2.1.1) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.1) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.1) lib/omniauth/strategy.rb:202:in `call!'
omniauth (2.1.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.1.1) lib/omniauth/builder.rb:44:in `call'
rack-attack (6.6.1) lib/rack/attack.rb:127:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
decidim-core (0.26.5) lib/decidim/middleware/strip_x_forwarded_host.rb:12:in `call'
decidim-decidim_awesome (0.8.3) app/middleware/decidim/decidim_awesome/current_config.rb:33:in `call'
decidim-core (0.26.5) lib/decidim/middleware/current_organization.rb:22:in `call'
rack (2.2.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.7) lib/rack/etag.rb:27:in `call'
rack (2.2.7) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.6.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.7) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.7) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/cookies.rb:654:in `call'
activerecord (6.0.6.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.6.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.6.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.4) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.7) lib/rack/method_override.rb:24:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.7) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
webpacker (6.0.0.rc.5) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.7.6) lib/rack/proxy.rb:87:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (5.6.5) lib/puma/configuration.rb:252:in `call'
puma (5.6.5) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.5) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.5) lib/puma/request.rb:76:in `handle_request'
puma (5.6.5) lib/puma/server.rb:443:in `process_client'
puma (5.6.5) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

@eliegaboriau while Lucie is not there, could you take a quick look at this issue?

**Comment by armandfardeau** [comment]
> * Add the new available locales in your `.env` file

Hi @paulinebessoles, do you work on a freshly created installation?

**Comment by paulinebessoles** [comment]
> Hi @paulinebessoles, do you work on a freshly created installation?

Yes! I just retested to be sure and I encounter the same issue.

**Review by paulinebessoles — APPROVED** [review]
My bad, I had a wrong config for the currency variable!

**Review by eliegaboriau — APPROVED** [review]

**Pull request merged**
