### PR TITLE
Fix/cannot change initiative type

### PR DESCRIPTION
**Pull request by Stef-Rousset**
#### :tophat: Description
As an admin, I cannot change the type of an initiative sent in technical validation for a type with global scope.

#### :pushpin: Related Issues
- Related to #483
- Fixes #?
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=3539854683bb4a2ab192a5c15c3bc6cf&pm=c)

#### Testing
*Describe the best way to test or validate your PR.*

1. Go to /admin/initiatives
2. Click on the initiative configuration button of an initiative sent in technical validation
3. Modify the "Type" field for a type wtih global scope
4. Update the changes
5. See that the new initiative type is applied

### CODE REVIEW

**Comment by Quentinchampenois** [comment]
Ready for review, CodeCov is blocking CI completion because of code coverage upload

**Review by BarbaraOliveira13 — DISMISSED** [review]
I tested in local 💯

**Review by Quentinchampenois — APPROVED** [review]
LGTM 

CI is failing because of CodeCov upload, will be fixed in another PR

**Review by luciegrau — DISMISSED** [review]
Works great, thank you! 
⚠️ DO NOT merge please, we are waiting for the v2.1.0 to be released!

**Pull request merged**
