### PR TITLE
Fix collaborative drafts

### PR DESCRIPTION
**Pull request by eliegaboriau**
#### Description

Fix collaborative show view

#### Tasks 
- [x] Fix collaborative show view
- [x] Add specs

### CODE REVIEW

**Review by paulinebessoles — APPROVED** [review]
Works perfectly, thank you @eliegaboriau!

**Review by armandfardeau — APPROVED** [review]

**Review by Quentinchampenois — APPROVED** [review]
LGTM !

**Comment by Quentinchampenois** [comment]
Note for next PR, a description is recommended for history ! 😄

**Comment by Quentinchampenois** [comment]
@eliegaboriau before merging can you add a note to `OVERLOADS.md` to be able to track overrides pls ?

**Pull request merged**
