### PR TITLE
feat: Use 6.0 default config (introduce Zeitwerk)

### PR DESCRIPTION
**Pull request by armandfardeau**
Use default param for 6.0 by default

previous params:

- action_controller.per_form_csrf_tokens = true
- action_controller.forgery_protection_origin_check = true
- ActiveSupport.to_time_preserves_timezone = true
- active_record.belongs_to_required_by_default = true
- self.ssl_options = { hsts: { subdomains: true } }
- assets.unknown_asset_fallback = false
- action_view.form_with_generates_remote_forms = true
- active_record.cache_versioning = true
- action_dispatch.use_authenticated_cookie_encryption = true
- active_support.use_authenticated_message_encryption = true
- active_support.use_sha1_digests = true
- action_controller.default_protect_from_forgery = true
- action_view.form_with_generates_ids = true

new params:

- action_controller.per_form_csrf_tokens = true
- action_controller.forgery_protection_origin_check = true
- ActiveSupport.to_time_preserves_timezone = true
- active_record.belongs_to_required_by_default = true
- self.ssl_options = { hsts: { subdomains: true } }
- assets.unknown_asset_fallback = false
- action_view.form_with_generates_remote_forms = true
- active_record.cache_versioning = true
- action_dispatch.use_authenticated_cookie_encryption = true
- active_support.use_authenticated_message_encryption = true
- active_support.use_sha1_digests = true
- action_controller.default_protect_from_forgery = true
- action_view.form_with_generates_ids = true
- self.autoloader = :zeitwerk if RUBY_ENGINE == "ruby"
- action_view.default_enforce_utf8 = false
- action_dispatch.use_cookies_with_metadata = true
- action_dispatch.return_only_media_type_on_content_type = false
- action_mailer.delivery_job = "ActionMailer::MailDeliveryJob"
- active_job.return_false_on_aborted_enqueue = true
- active_storage.queues.analysis = :active_storage_analysis
- active_storage.queues.purge    = :active_storage_purge
- active_storage.replace_on_assign_to_many = true
- active_record.collection_cache_versioning = true

For backports:

* run `bin/rails zeitwerk:check`

### CODE REVIEW

**Comment by Quentinchampenois** [comment]
Add `bin/rails zeitwerk:check` to CI linting step

**Comment by armandfardeau** [comment]
Need to be tested in production

**Review by AyakorK — APPROVED** [review]

**Review by Quentinchampenois — APPROVED** [review]

**Comment by luciegrau** [comment]
We need to check if the migration is valid before merging.

**Review by Quentinchampenois — CHANGES_REQUESTED** [review]
I found that containerized decidim-app isn't accessible because Rails 6 expect to add host in `config/environments/` file. 

We must find a way to add host in configs

See : Blocked host exception Rails 6

**Review by moustachu — APPROVED** [review]
Tested locally : 
- bundle
- de:reset + seed
- launch server

Tested on server : 
- production mode
- email configuration
- account creation

**Review by paulinebessoles — APPROVED** [review]

**Review by Quentinchampenois — APPROVED** [review]
Host issue mentioned previously is not related to this PR

**Pull request merged**
