### PR TITLE
[Feature] - omniauth france connect library

### PR DESCRIPTION
**Pull request by Quentinchampenois**
Add France Connect strategies 
* France Connect
* France Connect Profile
* France Connect UID

Add translations for Omniauth Publik

### CODE REVIEW

**Review by eliegaboriau — APPROVED** [review]

**Comment by paulinebessoles** [comment]
Hi @Quentinchampenois thank you for the feature 💪 !
I think we should also implement the FC logos, otherwise the integrations won't be accepted by FranceConnect. 
Do you know how we could do that?

**Comment by Quentinchampenois** [comment]
Hey @paulinebessoles, 

I've updated with the Fc icons, see how it looks like : 
Screenshot 2022-04-15 at 09 54 03

If you think about the display of the French National Assembly we must override the login view

**Comment by Quentinchampenois** [comment]
Also, we probably needs to override a behaviour since all our FC Connect buttons are named "Sign in with France"

**Comment by Quentinchampenois** [comment]
We must modify default SSO link for a France Connect image due to usage conditions. 
In progress

**Comment by Quentinchampenois** [comment]
We merge it for now, and add logos in new PR

**Pull request merged**
