### PR TITLE
Fix/rspec parallel

### PR DESCRIPTION
**Pull request by armandfardeau**

### CODE REVIEW

**Comment by armandfardeau** [comment]
> Hello @armandfardeau , Unless i missed something, the cd doesn't seems to launch every system spec, but only 2. It also doesn't seems to launch the i18n spec, which is failing locally.

Are you sure about this? I have no issue with `i18n_spec` whatoevers

**Comment by eliegaboriau** [comment]
> Are you sure about this? I have no issue with `i18n_spec` whatoevers

No, it's okay with the branch updated

**Comment by armandfardeau** [comment]
> > Are you sure about this? I have no issue with `i18n_spec` whatoevers
> 
> No, it's okay with the branch updated

Could you add your review please?

**Review by paulinebessoles — APPROVED** [review]

**Review by Quentinchampenois — APPROVED** [review]
LGTM

**Pull request merged**
