### PR TITLE
feat: Add multiple modules

### PR DESCRIPTION
**Pull request by AyakorK**
#### :tophat: Description
*Please describe your pull request.*

This PR adds few modules : 
- Budgets booth that will offer you the possibility to vote in a private space so the user cannot leave the vote phase
- Half Signup : Middleware mode that allows you to create an "half" account using your email or your phone number to make sure you can vote easily and in that mode it permits to make sure of the identity of the user each time she has to vote.

#### :pushpin: Related Issues

- [Notion card](https://www.notion.so/opensourcepolitics/Decidim-app-2-2-Ajout-module-half-sign-up-acdc92c247fa42db8cd4ca2afdad7e50?pvs=4)

### 💾  Backoffice setup
- Access to BackOffice
- Enable HalfSignup any method you want (may be great to test both of them individually then together)
- Go into a participatory process
- Click on categories
- Create some custom categories using the gem budget_category_voting (precompile deface if it's not displaying correctly)
- Access a budgets component settings
- Enable the option to ensure the user choose at least one project
- Access the budgets edition (not the setting but the place where every budgets are listed onto your component)
- Click on a budget
- Setup your budget using budget_category_voting  and select at least one project of a created category to make sure about the compatibility of budgets booth and budget_category_voting
- Access the projects onto your budget and modify some categories or create new ones to make sure your conditions can be fullfilled

##### ✂️ Half Signup account
- Click to vote
- Make sure you are redirected
- Put a random phone number (SMS method case)
- Put a random email (EMAIL method case)
- Follow the given instructions
- Access the budgets booth page
- Select your projects
- Leave the page by cancelling the vote
- You must be disconnected
- You should not be able to vote unless you selected a project of your required category
- Confirm your vote
- Make sure you are logged out afterwards

##### 🇪🇸 Decidim Account
- Log in as a decidim user
- Click to vote
- Make sure even if the activated that you're not redirected to the email confirmation (totally counterproductive regarding the UX)
- Put a phone number (If sms method is enabled)
- Verify that you are directly redirected to the budget (if sms method is disabled)
- Access the budgets booth page
- Select your projects
- You should not be able to vote unless you selected a project of your required category
- Leave the page by cancelling the vote
- You mustn't be disconnected
- Try to reaccess the same budget or another one
- Make sure you are redirected to the quick_auth page before accessing again to the vote (if sms method is enabled)

#### Tasks
- [x] Add modules
- [x] Change branch of EUF to ensure compatibility
- [x] Add migrations
- [x] Add an example gateway to test HalfSignup

### CODE REVIEW

**Review by Quentinchampenois — DISMISSED** [review]
Must be merged before https://github.com/OpenSourcePolitics/decidim-app/pull/519 for the `config.sms_gateway_service` configuration

**Review by luciegrau — CHANGES_REQUESTED** [review]
I think it's missing the addition of the `config/initializers/half_signup.rb` file with the following instructions: 
```
Decidim::HalfSignup.configure do |config|
  config.show_tos_page_after_signup = false
  # change this to false, if you don't want to redirect the user to the tos agreement page

  config.auth_code_length = 4
  # change this to other values if you want to change the length of generated code (be advised to remain in an acceptable limits for the sake of best performance)

  config.default_countries = [:fr]
  # change ':us' to the country/countries you want to be shown at the top(the first option will be selected by default).
end
```
We've added these configurations to decidim-tou and they'll be important for decidim-app instances (see https://github.com/OpenSourcePolitics/decidim-tou/pull/187).

**Comment by luciegrau** [comment]
I noticed a problem when testing the half sign up middleware module: after activating only authentication via SMS and voting, I can't vote again (even after entering another phone number). I'm redirected to the homepage and get a "You are not authorized to perform this action" message.

**Comment by luciegrau** [comment]
When I try the half sign up module locally, I encounter the following error: 
```
ActionView::Template::Error (undefined method `country_code' for nil:NilClass):
    1: <div class="row">
    2:   <div class="columns large-4">
    3:     <div class="field">
    4:       <%= form.select :phone_country, phone_country_options(form.object.phone_country), { id: "omniauth_country", include_blank: true }, class: "country-select" %>
    5:     </div>
    6:   </div>
    7:   <div class="columns large-8">
```

**Pull request merged**
