### PR TITLE
feat!: Bump 0.27

### PR DESCRIPTION
**Pull request by eliegaboriau**
BREAKING CHANGE: [everything](https://decidim.org/blog/2022-09-30-new-version-0-27-0/)

### Done : 
* Bump to ruby `3.0.6`
* add module `decidim-extended_socio_demographic_authorization_handler`
* Bump to Decidim `v0.27.4`
* Add new jobs

### CODE REVIEW

**Comment by armandfardeau** [comment]
Hello, please ignore coverage for this P.R.

**Review by armandfardeau — APPROVED** [review]

**Review by luciegrau — CHANGES_REQUESTED** [review]
Tried locally and I encountered several problems : 

- I can't log in as admin because I keep being asked to change my password ; 
- I get a server error when I try to access my account's notification settings (/notifications_settings) ; 
- The meeting map is not displayed (in any area of the platform) ; 
- I get a server error when I want to access a Meetings component but not the view of upcoming meetings (/meetings)

**Comment by luciegrau** [comment]
In order to make disable the admin password strong, we can add the following config `Decidim.config.admin_password_strong = false`  to the file `config/initializers/decidim.rb`

**Comment by armandfardeau** [comment]
Wait for https://github.com/PopulateTools/decidim-module-extra_user_fields/pull/17
Wait for https://github.com/OpenSourcePolitics/decidim-module-friendly_signup/pull/27

**Review by Quentinchampenois — CHANGES_REQUESTED** [review]

**Comment by Quentinchampenois** [comment]
Closed because of branch renamed 
PR/ #428

**Pull request closed without merging**
