### PR TITLE
Fix awesome tweaks style

### PR DESCRIPTION
**Pull request by Quentinchampenois**
#### Description

Fix custom styles from Decidim Awesome not loaded

#### Additional information

I haven't found a convenient way to mock the presence of module `Decidim::DecidimAwesome` for testing it when it is not defined, if there is ideas

I tried with `mock`, `stubs`, removing const from class (causing flaky)

### CODE REVIEW

**Review by armandfardeau — APPROVED** [review]

**Comment by paulinebessoles** [comment]
Thank you @Quentinchampenois ! I tested but it seems that for JS it's still not working

Head does not contain the required <script> Javascript entries. To solve it, you can manually add it to your custom `admin/_header.html.erb`:
```
<%= render partial: "layouts/decidim/decidim_awesome/awesome_config" %>
<%= javascript_include_tag "decidim/decidim_awesome/application" %>
```

Capture d’écran 2022-01-18 à 16 23 09

Do you think it could be done in this same PR?

**Review by paulinebessoles — CHANGES_REQUESTED** [review]
Thank you @Quentinchampenois ! I tested but it seems that for JS it's still not working

Head does not contain the required <script> Javascript entries. To solve it, you can manually add it to your custom `admin/_header.html.erb`:
```
<%= render partial: "layouts/decidim/decidim_awesome/awesome_config" %>
<%= javascript_include_tag "decidim/decidim_awesome/application" %>
```

Capture d’écran 2022-01-18 à 16 23 09

Do you think it could be done in this same PR?

**Comment by Quentinchampenois** [comment]
Yes I will fix it ASAP
Also I will : 
- [ ] Update overloads

**Review by paulinebessoles — APPROVED** [review]
Thank you Quentin, it's perfect! 👏

**Pull request merged**
