### PR TITLE
feat: Add module decidim-survey_multiple_answers

### PR DESCRIPTION
**Pull request by Quentinchampenois**
#### :tophat: Description
*Please describe your pull request.*

Add module `gem "decidim-survey_multiple_answers"`
#### :pushpin: Related Issues
*Link your PR to an issue*
- [Notion card](https://www.notion.so/opensourcepolitics/Decidim-app-0-27-module-gallery-et-module-Multiple-Survey-Answers-a57cff67d6ec478daea513c0a84029d7?pvs=4)

#### Tasks
- [x] Add module
- [x] Refactor extends loading

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

### CODE REVIEW

**Review by Quentinchampenois — COMMENTED** [review]
Product review passed in local : 
- Multiple answers 
- Exports 

Note: For admin, a unique answer is stored 
For anonymous and users OK

**Review by AyakorK — DISMISSED** [review]

**Review by luciegrau — COMMENTED** [review]
Hello Quentin, thank you for this new feature! 

I have few feedbacks: 

- When multiple answers are not allowed in the global settings of the survey feature, if I allow them in the step settings I can answer the survey several times 
- When multiple answers are allowed in the global settings but not allowed in the step settings I can also answer the survey several times 

I'm not sure that this corresponds to the desired behaviour of the module: in my opinion, if multiple answered are not allowed in global settings, I should not be able to answer the survey more than once, even if multiple answers are allowed in step settings. On the other hand, if multiple answers are allowed in the global settings but not in the active step settings, I shouldn't be able to answer the surveys several times. 

@Quentinchampenois @simonaszilinskas What do you think?

**Comment by simonaszilinskas** [comment]
Hello @luciegrau ! This is a great remark. We should investigate how similar features behave in order to have consistency. However, because:

1. the admin redesign will change phase config behaviour 
2. we have to deliver this feature ASAP and this is not a blocking issue

I would suggest to overlook this issue for now. What do you think?

**Comment by luciegrau** [comment]
Thank you @simonaszilinskas for your answer ! 
In fact, this behaviour is not similar to that of the Proposal or Budget components for example. Activating an option in the global settings does not override the step settings. Similarly, an option cannot be active, even if it is enabled in the step settings, if it has not been activated in the global settings. 
I'm sure that this doesn't prevent the module from being used by the customer who ordered it, but I think that fixing this behaviour is important because we're exposing ourselves to customer support because it can create confusion for them. If Quentin thinks that fixing it isn't too complicated, given the urgency of the delivery, I think it's important that we take the time to fix it before delivering it.

**Comment by Quentinchampenois** [comment]
Switch state to draft waiting for product review to be approved

**Comment by Quentinchampenois** [comment]
Bump module and review

**Comment by simonaszilinskas** [comment]
I agree and will forward this to Alex. However, did you check if this weird logged in behaviour is only present as an admin? I think that was the case.

**Comment by luciegrau** [comment]
@simonaszilinskas Thanks for the remark, indeed this behaviour is only present if I'm logged in as admin (@Quentinchampenois already mentioned it in a previous comment). I still think we should fix this behaviour because it could create confusion for administrators, but I understand that it is not usual for admins to answer a published survey just as users. What do you think ?

**Comment by simonaszilinskas** [comment]
Le fix arrive dans une nouvelle release dans quelques heures @luciegrau @Quentinchampenois

**Comment by simonaszilinskas** [comment]
https://rubygems.org/gems/decidim-survey_multiple_answers

**Review by luciegrau — DISMISSED** [review]
After another product review, everything seems to be working fine! So I think we can add the module to our next release. Thanks for all your hard work and for all the changes you've made in response to the feedback 💯

**Review by AyakorK — DISMISSED** [review]

**Review by AyakorK — APPROVED** [review]

**Pull request merged**
