### PR TITLE
Fix - FranceConnect Requests (Images - Modal - OkText) (RE-RUN)

### PR DESCRIPTION
**Pull request by AyakorK**
Hello ! I'm currently doing this pull request to submit to you some changes on the DCD app related to FranceConnect design.

Firstly, chaning the image of our buttons to respond to the request of FranceConnect, then in addition of that, add the button to the login modal, and finally add an help text on the modification of the password to prevent the user from modifying his password if he tries to connect using his FC password on our instance of decidim.

In addition of that, something that wasn't in the initial issue, I had to modify the structure of omniauth_buttons because if we had at least one media that wasn't FranceConnect in addition of the FC, we had the same message "What is FranceConnect" below the button, which does obviously not apply to Twitter or Facebook for example.

**_This PR is linked to and the same that #193 but tried to make an other pull request to make sure checks are running._**

### CODE REVIEW

**Review by Quentinchampenois — APPROVED** [review]
Can you add the overrides in the dedicated file pls ?

**Comment by paulinebessoles** [comment]
@Quentinchampenois we have a problem with the actions, do you know how we could relaunch them?

**Comment by Quentinchampenois** [comment]
@paulinebessoles I don't know why CI is stuck, I will probably clone this branch and push on this repository, I am on it

**Comment by Quentinchampenois** [comment]
Cloned on #206

**Pull request closed without merging**
